import {test,expect} from '@playwright/test';
import {pageResponse,overviewResponse} from './page-fixture.js';

const revision=(id,html,{role='student',kind='submission',number=Number(id)}={})=>({id:String(id),authorRole:role,revisionKind:kind,revisionNumber:number,contentHtml:html,createdAt:`2026-10-0${Math.min(number,9)}T05:00:00Z`});
async function setup(page,revisions=[revision(1,'<p>처음 원고</p>'),revision(2,'<p>새로운 원고</p>',{kind:'resubmission'})],extra={}){
  const article={id:'diff-article',studentId:'student',authorName:'11001 학생',native:true,articleType:'school',titleKo:'한글 English 비교 기사',titleEn:'',draftHtml:revisions.filter(r=>r.authorRole==='student'&&r.revisionKind!=='import').at(-1)?.contentHtml||'<p>원고</p>',editorDraftHtml:'<p>교사 첨삭 본문</p>',studentFeedback:'피드백',internalNote:'PRIVATE NOTE',status:'reviewing',updatedAt:'2026-10-08T00:00:00Z',revisions,...extra},calls=[];
  await page.route('**/api/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname;calls.push({path,method:request.method()});let data;
    if(path==='/api/session')data={authenticated:true,user:{role:'admin',name:'관리자',studentId:'admin'}};
    else if(path==='/api/assignments')data={campaigns:[],assignments:[]};
    else if(path==='/api/admin/article-overview')data=overviewResponse([article]);
    else if(path==='/api/native/articles')data=pageResponse([article]);
    else if(path==='/api/native/articles/diff-article')data=article;
    else if(path.endsWith('/editor')){article.editorDraftHtml=request.postDataJSON().contentHtml;data=article;}
    else throw new Error('Unexpected API '+path);
    await route.fulfill({json:data});
  });
  await page.goto('/admin/#view=articles&article=diff-article');await expect(page.locator('[data-editor]')).toBeVisible();return {article,calls};
}
async function open(page){await page.locator('[data-compare-submissions]').click();await expect(page.locator('.submission-diff-dialog')).toBeVisible();return page.locator('.submission-diff-dialog');}
test('first submission has explanation and disabled comparison',async({page})=>{await setup(page,[revision(1,'<p>처음</p>'),revision(2,'<p>teacher</p>',{role:'admin',kind:'editor_save'})]);await expect(page.locator('[data-compare-submissions]')).toBeDisabled();await expect(page.locator('.composer-top')).toContainText('이전 학생 제출본이 없어');});
test('resubmission uses previous/latest student bodies; no extra API or stored draft mutation',async({page})=>{
  const state=await setup(page,[revision(1,'<p>오늘 학교에서 news를 읽었습니다.</p>'),revision(2,'<p>TEACHER EDIT</p>',{role:'admin',kind:'editor_save'}),revision(3,'<p>오늘 학교에서 새로운 news를 읽었습니다.</p>',{kind:'resubmission'}),revision(4,'<p>IMPORT DRAFT</p>',{kind:'import'})]);const before=state.calls.length,stored=JSON.stringify(state.article),dialog=await open(page);
  await expect(dialog.locator('ins')).toContainText('새로운');await expect(dialog.locator('del')).toHaveCount(0);await expect(dialog.locator('[data-diff-body]')).not.toContainText('TEACHER');await expect(dialog.locator('[data-diff-body]')).not.toContainText('IMPORT');await expect(dialog.locator('[data-diff-body]')).not.toContainText('PRIVATE NOTE');expect(state.calls.length).toBe(before);expect(JSON.stringify(state.article)).toBe(stored);
});
test('multiple resubmissions default to previous; older selection updates counts',async({page})=>{await setup(page,[revision(1,'<p>A</p>'),revision(2,'<p>A B</p>',{kind:'resubmission'}),revision(3,'<p>A B C</p>',{kind:'resubmission'})]);const dialog=await open(page);await expect(dialog.locator('select')).toHaveValue('2');await expect(dialog.locator('[data-diff-counts]')).toContainText('이전 3자');await dialog.locator('select').selectOption('1');await expect(dialog.locator('[data-diff-counts]')).toContainText('이전 1자');await expect(dialog.locator('[data-diff-counts]')).toContainText('현재 5자');await expect(dialog.locator('[data-diff-counts]')).toContainText('추가 4자');});
test('unchanged body reports zero; paragraph/BR/CRLF match existing counting',async({page})=>{await setup(page,[revision(1,'<p>A<br>B</p><p>é 👩‍💻</p>'),revision(2,'<div>A\r\nB</div><p>é 👩‍💻</p>',{kind:'resubmission'})]);const dialog=await open(page);await expect(dialog.locator('[data-diff-status]')).toHaveText('본문 변경이 없습니다.');await expect(dialog.locator('[data-diff-counts]')).toHaveText('이전 7자현재 7자추가 0자삭제 0자');await expect(dialog.locator('[data-diff-next]')).toBeDisabled();});
test('whitespace/paragraph changes have semantic insert/delete and readable labels',async({page})=>{await setup(page,[revision(1,'<p>A B</p><p>삭제 문단</p>'),revision(2,'<p>A  B</p><p>추가 문단<br>새 줄</p>',{kind:'resubmission'})]);const dialog=await open(page);await expect(dialog.locator('ins')).not.toHaveCount(0);await expect(dialog.locator('del')).not.toHaveCount(0);await expect(dialog.locator('.diff-legend')).toContainText('추가 · 밑줄');await expect(dialog.locator('.diff-legend')).toContainText('삭제 · 취소선');expect(await dialog.locator('[data-diff-body]').textContent()).toContain('\n');});
test('space-only differences are explicit',async({page})=>{await setup(page,[revision(1,'<p>A B</p>'),revision(2,'<p>A  B</p>',{kind:'resubmission'})]);const dialog=await open(page);await expect(dialog.locator('.diff-marker').first()).toContainText('공백');});
test('stored HTML and title XSS never become executable comparison DOM',async({page})=>{
  await setup(page,[revision(1,'<p>안전 &lt;img src=x onerror=alert(1)&gt;</p><script>window.diffXss=1</script>'),revision(2,'<p><span onclick="window.diffXss=1">수정 &lt;script&gt;</span></p><svg onload="window.diffXss=1"></svg>',{kind:'resubmission'})],{titleKo:'<img src=x onerror="window.diffXss=1"> 기사'});const dialog=await open(page);
  await expect(dialog.locator('h2')).toContainText('<img');await expect(dialog.locator('script,img,svg,[onclick]')).toHaveCount(0);expect(await page.evaluate(()=>window.diffXss)).toBeUndefined();expect(await dialog.locator('[data-diff-body]').evaluate(node=>{const copy=node.cloneNode(true);copy.querySelectorAll('del,.diff-marker,summary').forEach(n=>n.remove());return copy.textContent;})).toBe('수정 <script>');
});
test('modal focus/trap/Escape/restore and scroll lock preserve current editor',async({page})=>{
  const s=await setup(page);await page.locator('[data-editor]').fill('현재 첨삭 입력');const before=s.calls.length;await open(page);await expect(page.locator('html')).toHaveCSS('overflow','hidden');await page.locator('[data-diff-next]').focus();await page.keyboard.press('Tab');await expect(page.locator('[data-diff-close]')).toBeFocused();await page.keyboard.press('Escape');await expect(page.locator('.submission-diff-dialog')).toHaveCount(0);await expect(page.locator('[data-compare-submissions]')).toBeFocused();await expect(page.locator('[data-editor]')).toHaveText('현재 첨삭 입력');expect(s.calls.slice(before).filter(c=>c.method!=='GET').every(c=>c.path.endsWith('/editor'))).toBe(true);
});
test('long manuscript collapses unchanged context; next/previous navigate change targets',async({page})=>{const prefix='학교 English news 원고.\n'.repeat(3000);await setup(page,[revision(1,`<p>${prefix}이전 문장</p>`),revision(2,`<p>${prefix}새로운 문장</p>`,{kind:'resubmission'})]);const start=Date.now(),dialog=await open(page);await expect(dialog.locator('details')).toHaveCount(1);expect(Date.now()-start).toBeLessThan(5000);await dialog.locator('[data-diff-next]').click();await expect(dialog.locator('[data-diff-position]')).toHaveText(/1 \/ /);await expect(dialog.locator('del').first()).toBeFocused();await dialog.locator('[data-diff-next]').click();await expect(dialog.locator('ins').first()).toBeFocused();await dialog.locator('summary').click();await expect(dialog.locator('details')).toHaveAttribute('open','');});
test('large replacement uses bounded grouped fallback',async({page})=>{await setup(page,[revision(1,'<p>'+'old word '.repeat(8000)+'</p>'),revision(2,'<p>'+'새로운 문장 '.repeat(8000)+'</p>',{kind:'resubmission'})]);const dialog=await open(page);await expect(dialog.locator('[data-diff-status]')).toContainText('구간을 묶어');await expect(dialog.locator('ins')).toHaveCount(1);await expect(dialog.locator('del')).toHaveCount(1);});
for(const width of [390,820,1440])test('comparison layout '+width,async({page},info)=>{
  await page.setViewportSize({width,height:850});await setup(page,[revision(1,'<p>한글 English 이전 문단\n긴제목과공백없는원고'.repeat(20)+'</p>'),revision(2,'<p>한글 English 최신 문단\n긴제목과공백없는원고'.repeat(20)+'</p>',{kind:'resubmission'})],{titleKo:'긴 제목 · 한글 English 기사 수정 내용 확인 '.repeat(6)});const dialog=await open(page);await expect(dialog).toBeVisible();await expect(dialog.locator('[data-diff-close]')).toHaveCSS('white-space','nowrap');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const box=await dialog.boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width);expect(await dialog.evaluate(d=>d.scrollWidth<=d.clientWidth)).toBe(true);await page.screenshot({path:info.outputPath('diff-'+width+'.png')});
});
test('reduced-motion change navigation and same text remain usable',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await setup(page);const dialog=await open(page);await dialog.locator('[data-diff-next]').click();await expect(dialog.locator('[data-diff-position]')).toContainText('1 /');await expect(dialog.locator('del').first()).toBeFocused();});
test('switching prior submission while background diff is pending cannot apply stale result',async({page})=>{
  let requests=0;await page.route('**/submission-diff-background.js',async route=>{const response=await route.fetch();let text=await response.text();if(++requests===1)text+='\nconst original=self.onmessage;self.onmessage=event=>setTimeout(()=>original(event),600);';await route.fulfill({response,body:text});});
  const s=await setup(page,[revision(1,'<p>'+'오래된 원고 '.repeat(4000)+'</p>'),revision(2,'<p>'+'직전 원고 '.repeat(4000)+'</p>',{kind:'resubmission'}),revision(3,'<p>'+'최신 원고 '.repeat(4000)+'</p>',{kind:'resubmission'})]);const before=s.calls.length,dialog=await open(page);await dialog.locator('select').selectOption('1');await expect(dialog.locator('[data-diff-counts]')).toContainText('이전 28,000자');await expect(dialog.locator('[data-diff-status]')).not.toHaveText('비교하는 중…');await page.waitForTimeout(700);await expect(dialog.locator('[data-diff-counts]')).toContainText('이전 28,000자');expect(s.calls.length).toBe(before);
});
test('background module failure leaves clear retry state instead of indefinite comparison',async({page})=>{
  await page.route('**/submission-diff-background.js',route=>route.abort());await setup(page,[revision(1,'<p>'+'원래 원고 '.repeat(6000)+'</p>'),revision(2,'<p>'+'새로운 원고 '.repeat(6000)+'</p>',{kind:'resubmission'})]);const dialog=await open(page);await expect(dialog.locator('[data-diff-status]')).toContainText('비교에 실패');await expect(dialog.locator('[data-diff-next]')).toBeDisabled();await dialog.locator('[data-diff-close]').click();await expect(page.locator('[data-editor]')).toBeVisible();
});
test('oversized legacy submission has clear guard; no API writes and original preserved',async({page})=>{
  const state=await setup(page,[revision(1,'<p>'+'a'.repeat(310000)+'</p>'),revision(2,'<p>'+'b'.repeat(310000)+'</p>',{kind:'resubmission'})]);const original=JSON.stringify(state.article),before=state.calls.length,dialog=await open(page);await expect(dialog.locator('[data-diff-status]')).toContainText('너무 길');expect(JSON.stringify(state.article)).toBe(original);expect(state.calls.length).toBe(before);
});
