const now = () => new Date().toISOString();
const json = value => JSON.stringify(value ?? []);
const parseIssue = row => row && ({ id: row.id, name: row.name, year: row.year, season: row.season, status: row.status, classroomCourseId: row.classroom_course_id, articleTypes: JSON.parse(row.article_types_json), createdAt: row.created_at, updatedAt: row.updated_at });
const parseNativeArticle = row => row && ({
  id:row.id, issueId:row.issue_id, studentId:row.student_id, articleType:row.article_type,
  titleKo:row.title_ko, titleEn:row.title_en, status:row.status, draftHtml:row.draft_html,
  editorDraftHtml:row.editor_draft_html, currentStudentRevisionId:row.current_student_revision_id,
  currentEditorRevisionId:row.current_editor_revision_id, createdAt:row.created_at,
  updatedAt:row.updated_at, submittedAt:row.submitted_at,
  studentFeedback:row.student_feedback || '', internalNote:row.internal_note || ''
});

export class D1EditorialRepository {
  constructor(db) { this.db = db; }
  async listIssues() { const { results } = await this.db.prepare('SELECT * FROM issues ORDER BY created_at DESC').all(); return results.map(parseIssue); }
  async getIssue(id) { return parseIssue(await this.db.prepare('SELECT * FROM issues WHERE id=?').bind(id).first()); }
  async createIssue(input) {
    const timestamp = now(), id = crypto.randomUUID();
    await this.db.prepare('INSERT INTO issues(id,name,year,season,status,classroom_course_id,article_types_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,input.name,input.year,input.season,input.status || 'draft',input.classroomCourseId,json(input.articleTypes),timestamp,timestamp).run();
    return this.getIssue(id);
  }
  async setActiveIssue(id) { const timestamp=now(); await this.db.batch([this.db.prepare("UPDATE issues SET status='draft',updated_at=? WHERE status='active'").bind(timestamp),this.db.prepare("UPDATE issues SET status='active',updated_at=? WHERE id=?").bind(timestamp,id)]); const issue=await this.getIssue(id); if(!issue)throw Object.assign(new Error('Issue not found.'),{status:404,code:'issue_not_found'}); return issue; }
  async listEdits(issueId, studentId) { let q='SELECT * FROM article_edits WHERE issue_id=?', args=[issueId]; if(studentId){q+=' AND student_google_id=?';args.push(studentId);} return (await this.db.prepare(q).bind(...args).all()).results; }
  async getEdit(id) { return this.db.prepare('SELECT * FROM article_edits WHERE submission_id=?').bind(id).first(); }
  async saveEdit(id, input, actorId) { const timestamp=now(); await this.db.prepare(`INSERT INTO article_edits(submission_id,issue_id,course_id,course_work_id,student_google_id,edited_html,editor_note,note_visibility,status,updated_by_google_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(submission_id) DO UPDATE SET edited_html=excluded.edited_html,editor_note=excluded.editor_note,note_visibility=excluded.note_visibility,status=excluded.status,updated_by_google_id=excluded.updated_by_google_id,updated_at=excluded.updated_at`).bind(id,input.issueId,input.courseId,input.courseWorkId,input.studentGoogleId,input.editedHtml,input.editorNote,input.noteVisibility,input.status||'reviewing',actorId,timestamp,timestamp).run(); return this.getEdit(id); }
  async createPhoto(input) { const id=crypto.randomUUID(), timestamp=now(); await this.db.prepare('INSERT INTO photos(id,issue_id,article_submission_id,article_id,student_google_id,drive_file_id,filename,mime_type,byte_size,caption,photographer,source_type,rights_confirmed,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,input.issueId,input.articleSubmissionId,input.articleId||null,input.studentGoogleId,input.driveFileId,input.filename,input.mimeType,input.byteSize,input.caption,input.photographer,input.sourceType,input.rightsConfirmed?1:0,'unreviewed',timestamp,timestamp).run(); return this.getPhoto(id); }
  async listPhotos(issueId, studentId) { let q='SELECT * FROM photos WHERE issue_id=?',args=[issueId];if(studentId){q+=' AND student_google_id=?';args.push(studentId);}return (await this.db.prepare(q).bind(...args).all()).results; }
  async getPhoto(id) { return this.db.prepare('SELECT * FROM photos WHERE id=?').bind(id).first(); }
  async updatePhotoStatus(id,status){await this.db.prepare('UPDATE photos SET status=?,updated_at=? WHERE id=?').bind(status,now(),id).run();const row=await this.db.prepare('SELECT * FROM photos WHERE id=?').bind(id).first();if(!row)throw Object.assign(new Error('Photo not found.'),{status:404,code:'photo_not_found'});return row;}
  async listNativeArticles(studentId) { let q=`SELECT a.*,f.student_feedback,f.internal_note FROM articles a LEFT JOIN article_feedback f ON f.article_id=a.id`; const args=[]; if(studentId){q+=' WHERE a.student_id=?';args.push(studentId);} q+=' ORDER BY a.updated_at DESC'; return (await this.db.prepare(q).bind(...args).all()).results.map(parseNativeArticle); }
  async getNativeArticle(id) { return parseNativeArticle(await this.db.prepare(`SELECT a.*,f.student_feedback,f.internal_note FROM articles a LEFT JOIN article_feedback f ON f.article_id=a.id WHERE a.id=?`).bind(id).first()); }
  async createNativeArticle(input, studentId) { const id=crypto.randomUUID(),timestamp=now(); await this.db.prepare(`INSERT INTO articles(id,issue_id,student_id,article_type,title_ko,title_en,status,draft_html,created_at,updated_at) VALUES(?,?,?,?,?,?,'draft',?,?,?)`).bind(id,input.issueId||null,studentId,input.articleType,input.titleKo,input.titleEn,input.contentHtml||'',timestamp,timestamp).run(); return this.getNativeArticle(id); }
  async saveStudentDraft(id,input) { await this.db.prepare(`UPDATE articles SET article_type=?,title_ko=?,title_en=?,draft_html=?,updated_at=? WHERE id=?`).bind(input.articleType,input.titleKo,input.titleEn,input.contentHtml,now(),id).run(); return this.getNativeArticle(id); }
  async addRevision(article,actorId,role,kind,contentHtml) { const id=crypto.randomUUID(),timestamp=now(); const count=await this.db.prepare('SELECT COALESCE(MAX(revision_number),0)+1 n FROM article_revisions WHERE article_id=?').bind(article.id).first(); await this.db.prepare(`INSERT INTO article_revisions(id,article_id,author_user_id,author_role,revision_kind,title_ko,title_en,content_html,revision_number,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id,article.id,actorId,role,kind,article.titleKo,article.titleEn,contentHtml,Number(count.n),timestamp).run(); return id; }
  async submitNativeArticle(article,actorId) { const revisionId=await this.addRevision(article,actorId,'student',article.status==='revision_requested'?'resubmission':'submission',article.draftHtml); const timestamp=now(); await this.db.prepare(`UPDATE articles SET status='submitted',current_student_revision_id=?,submitted_at=?,updated_at=? WHERE id=?`).bind(revisionId,timestamp,timestamp,article.id).run(); return this.getNativeArticle(article.id); }
  async saveEditorDraft(article,input,actorId) { const content=input.contentHtml; const revisionId=input.checkpoint ? await this.addRevision({...article,titleKo:input.titleKo||article.titleKo,titleEn:input.titleEn||article.titleEn},actorId,'admin','editor_save',content) : null; await this.db.batch([this.db.prepare(`UPDATE articles SET title_ko=?,title_en=?,editor_draft_html=?,current_editor_revision_id=COALESCE(?,current_editor_revision_id),updated_at=? WHERE id=?`).bind(input.titleKo||article.titleKo,input.titleEn||article.titleEn,content,revisionId,now(),article.id),this.db.prepare(`INSERT INTO article_feedback(article_id,student_feedback,internal_note,updated_by_user_id,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(article_id) DO UPDATE SET student_feedback=excluded.student_feedback,internal_note=excluded.internal_note,updated_by_user_id=excluded.updated_by_user_id,updated_at=excluded.updated_at`).bind(article.id,input.studentFeedback||'',input.internalNote||'',actorId,now())]); return this.getNativeArticle(article.id); }
  async setNativeStatus(article,status,actorId) { let revisionId=null; if(['approved','scheduled','revision_requested'].includes(status)) revisionId=await this.addRevision(article,actorId,'admin','status_change',article.editorDraftHtml||article.draftHtml); await this.db.prepare(`UPDATE articles SET status=?,current_editor_revision_id=COALESCE(?,current_editor_revision_id),updated_at=? WHERE id=?`).bind(status,revisionId,now(),article.id).run(); return this.getNativeArticle(article.id); }
  async listRevisions(articleId) { return (await this.db.prepare(`SELECT id,article_id articleId,author_role authorRole,revision_kind revisionKind,title_ko titleKo,title_en titleEn,content_html contentHtml,revision_number revisionNumber,created_at createdAt FROM article_revisions WHERE article_id=? ORDER BY revision_number DESC`).bind(articleId).all()).results; }
}

export function repository(env) {
  if (!env.DB) throw Object.assign(new Error('D1 binding DB is required for production persistence.'), { status: 503, code: 'database_unconfigured' });
  return new D1EditorialRepository(env.DB);
}
