const now = () => new Date().toISOString();
const json = value => JSON.stringify(value ?? []);
const parseIssue = row => row && ({ id: row.id, name: row.name, year: row.year, season: row.season, status: row.status, classroomCourseId: row.classroom_course_id, articleTypes: JSON.parse(row.article_types_json), createdAt: row.created_at, updatedAt: row.updated_at });
const parseNativeArticle = row => row && ({
  id:row.id, issueId:row.issue_id, studentId:row.student_id, articleType:row.article_type,
  titleKo:row.title_ko, titleEn:row.title_en, status:row.status, draftHtml:row.draft_html,
  editorDraftHtml:row.editor_draft_html, currentStudentRevisionId:row.current_student_revision_id,
  currentEditorRevisionId:row.current_editor_revision_id, createdAt:row.created_at,
  updatedAt:row.updated_at, submittedAt:row.submitted_at,
  studentFeedback:row.student_feedback || '', internalNote:row.internal_note || '',
  assignmentInstanceId:row.assignment_instance_id || null, assignmentSlotId:row.assignment_slot_id || null,
  campaignId:row.campaign_id || null, assignmentName:row.assignment_name || '', slotName:row.slot_name || '',
  assignmentDueAt:row.assignment_due_at || null, slotDueAt:row.slot_due_at || null
});
const parseCampaign = row => row && ({id:row.id,name:row.name,year:row.year,issueLabel:row.issue_label,issueId:row.issue_id,instructions:row.instructions,startsAt:row.starts_at,dueAt:row.due_at,status:row.status,audienceMode:row.audience_mode,distributedAt:row.distributed_at,createdAt:row.created_at,updatedAt:row.updated_at});
const parseSlot = row => row && ({id:row.id,campaignId:row.campaign_id,articleType:row.article_type,displayName:row.display_name,required:Boolean(row.required),quantity:row.quantity,dueAt:row.due_at,instructions:row.instructions,position:row.position});

export class D1EditorialRepository {
  constructor(db) { this.db = db; }
  async listIssues() { const { results } = await this.db.prepare('SELECT * FROM issues ORDER BY created_at DESC').all(); return results.map(parseIssue); }
  async getIssue(id) { return parseIssue(await this.db.prepare('SELECT * FROM issues WHERE id=?').bind(id).first()); }
  async createIssue(input) {
    const timestamp = now(), id = crypto.randomUUID();
    await this.db.prepare('INSERT INTO issues(id,name,year,season,status,classroom_course_id,article_types_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,input.name,input.year,input.season,input.status || 'draft',input.classroomCourseId,json(input.articleTypes),timestamp,timestamp).run();
    return this.getIssue(id);
  }
  async setActiveIssue(id) { const timestamp=now(); await this.db.batch([this.db.prepare("UPDATE issues SET status='draft',updated_at=? WHERE status='active'").bind(timestamp),this.db.prepare("UPDATE issues SET status='active',updated_at=? WHERE id=?").bind(timestamp,id)]); const issue=await this.getIssue(id); if(!issue)throw Object.assign(new Error('Issue not found.'),{status:404,code:'issue_not_found'}); return issue; }
  async listEdits(issueId, studentId) { let q='SELECT * FROM article_edits WHERE issue_id=?', args=[issueId]; if(studentId){q+=' AND student_google_id=?';args.push(studentId);} return (await this.db.prepare(q).bind(...args).all()).results; }
  async getEdit(id) { return this.db.prepare('SELECT * FROM article_edits WHERE submission_id=?').bind(id).first(); }
  async saveEdit(id, input, actorId) { const timestamp=now(); await this.db.prepare(`INSERT INTO article_edits(submission_id,issue_id,course_id,course_work_id,student_google_id,edited_html,editor_note,note_visibility,status,updated_by_google_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(submission_id) DO UPDATE SET edited_html=excluded.edited_html,editor_note=excluded.editor_note,note_visibility=excluded.note_visibility,status=excluded.status,updated_by_google_id=excluded.updated_by_google_id,updated_at=excluded.updated_at`).bind(id,input.issueId,input.courseId,input.courseWorkId,input.studentGoogleId,input.editedHtml,input.editorNote,input.noteVisibility,input.status||'reviewing',actorId,timestamp,timestamp).run(); return this.getEdit(id); }
  async createPhoto(input) { const id=crypto.randomUUID(), timestamp=now(); await this.db.prepare('INSERT INTO photos(id,issue_id,article_submission_id,article_id,student_google_id,drive_file_id,filename,mime_type,byte_size,caption,photographer,source_type,rights_confirmed,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,input.issueId,input.articleSubmissionId,input.articleId||null,input.studentGoogleId,input.driveFileId,input.filename,input.mimeType,input.byteSize,input.caption,input.photographer,input.sourceType,input.rightsConfirmed?1:0,'unreviewed',timestamp,timestamp).run(); return this.getPhoto(id); }
  async listPhotos(issueId, studentId) { let q='SELECT * FROM photos WHERE issue_id=?',args=[issueId];if(studentId){q+=' AND student_google_id=?';args.push(studentId);}return (await this.db.prepare(q).bind(...args).all()).results; }
  async getPhoto(id) { return this.db.prepare('SELECT * FROM photos WHERE id=?').bind(id).first(); }
  async updatePhotoStatus(id,status){await this.db.prepare('UPDATE photos SET status=?,updated_at=? WHERE id=?').bind(status,now(),id).run();const row=await this.db.prepare('SELECT * FROM photos WHERE id=?').bind(id).first();if(!row)throw Object.assign(new Error('Photo not found.'),{status:404,code:'photo_not_found'});return row;}
  articleSelect(){return `SELECT a.*,f.student_feedback,f.internal_note,asi.id assignment_instance_id,asi.slot_id assignment_slot_id,asi.campaign_id,c.name assignment_name,s.display_name slot_name,c.due_at assignment_due_at,s.due_at slot_due_at FROM articles a LEFT JOIN article_feedback f ON f.article_id=a.id LEFT JOIN assignment_slot_instances asi ON asi.article_id=a.id LEFT JOIN assignment_campaigns c ON c.id=asi.campaign_id LEFT JOIN assignment_slots s ON s.id=asi.slot_id`;}
  async listNativeArticles(studentId) { let q=this.articleSelect(); const args=[]; if(studentId){q+=' WHERE a.student_id=?';args.push(studentId);} q+=' ORDER BY a.updated_at DESC'; return (await this.db.prepare(q).bind(...args).all()).results.map(parseNativeArticle); }
  async getNativeArticle(id) { return parseNativeArticle(await this.db.prepare(`${this.articleSelect()} WHERE a.id=?`).bind(id).first()); }
  async createNativeArticle(input, studentId) { const id=crypto.randomUUID(),timestamp=now(); await this.db.prepare(`INSERT INTO articles(id,issue_id,student_id,article_type,title_ko,title_en,status,draft_html,created_at,updated_at) VALUES(?,?,?,?,?,?,'draft',?,?,?)`).bind(id,input.issueId||null,studentId,input.articleType,input.titleKo,input.titleEn,input.contentHtml||'',timestamp,timestamp).run(); return this.getNativeArticle(id); }
  async saveStudentDraft(id,input) { await this.db.prepare(`UPDATE articles SET article_type=?,title_ko=?,title_en=?,draft_html=?,updated_at=? WHERE id=?`).bind(input.articleType,input.titleKo,input.titleEn,input.contentHtml,now(),id).run(); return this.getNativeArticle(id); }
  async addRevision(article,actorId,role,kind,contentHtml) { const id=crypto.randomUUID(),timestamp=now(); const count=await this.db.prepare('SELECT COALESCE(MAX(revision_number),0)+1 n FROM article_revisions WHERE article_id=?').bind(article.id).first(); await this.db.prepare(`INSERT INTO article_revisions(id,article_id,author_user_id,author_role,revision_kind,title_ko,title_en,content_html,revision_number,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id,article.id,actorId,role,kind,article.titleKo,article.titleEn,contentHtml,Number(count.n),timestamp).run(); return id; }
  async submitNativeArticle(article,actorId) { const revisionId=await this.addRevision(article,actorId,'student',article.status==='revision_requested'?'resubmission':'submission',article.draftHtml); const timestamp=now(); await this.db.prepare(`UPDATE articles SET status='submitted',current_student_revision_id=?,submitted_at=?,updated_at=? WHERE id=?`).bind(revisionId,timestamp,timestamp,article.id).run(); return this.getNativeArticle(article.id); }
  async saveEditorDraft(article,input,actorId) { const content=input.contentHtml; const revisionId=input.checkpoint ? await this.addRevision({...article,titleKo:input.titleKo||article.titleKo,titleEn:input.titleEn||article.titleEn},actorId,'admin','editor_save',content) : null; await this.db.batch([this.db.prepare(`UPDATE articles SET title_ko=?,title_en=?,editor_draft_html=?,current_editor_revision_id=COALESCE(?,current_editor_revision_id),updated_at=? WHERE id=?`).bind(input.titleKo||article.titleKo,input.titleEn||article.titleEn,content,revisionId,now(),article.id),this.db.prepare(`INSERT INTO article_feedback(article_id,student_feedback,internal_note,updated_by_user_id,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(article_id) DO UPDATE SET student_feedback=excluded.student_feedback,internal_note=excluded.internal_note,updated_by_user_id=excluded.updated_by_user_id,updated_at=excluded.updated_at`).bind(article.id,input.studentFeedback||'',input.internalNote||'',actorId,now())]); return this.getNativeArticle(article.id); }
  async setNativeStatus(article,status,actorId) { let revisionId=null; if(['approved','scheduled','revision_requested'].includes(status)) revisionId=await this.addRevision(article,actorId,'admin','status_change',article.editorDraftHtml||article.draftHtml); await this.db.prepare(`UPDATE articles SET status=?,current_editor_revision_id=COALESCE(?,current_editor_revision_id),updated_at=? WHERE id=?`).bind(status,revisionId,now(),article.id).run(); return this.getNativeArticle(article.id); }
  async listRevisions(articleId) { return (await this.db.prepare(`SELECT id,article_id articleId,author_role authorRole,revision_kind revisionKind,title_ko titleKo,title_en titleEn,content_html contentHtml,revision_number revisionNumber,created_at createdAt FROM article_revisions WHERE article_id=? ORDER BY revision_number DESC`).bind(articleId).all()).results; }
  async createCampaign(input,actorId){const id=crypto.randomUUID(),timestamp=now();const slots=input.slots.map((slot,index)=>({id:crypto.randomUUID(),...slot,position:index}));await this.db.batch([this.db.prepare(`INSERT INTO assignment_campaigns(id,name,year,issue_label,issue_id,instructions,starts_at,due_at,status,audience_mode,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'draft',?,?,?,?)`).bind(id,input.name,input.year,input.issueLabel,input.issueId,input.instructions,input.startsAt,input.dueAt,input.audienceMode,actorId,timestamp,timestamp),...slots.map(slot=>this.db.prepare(`INSERT INTO assignment_slots(id,campaign_id,article_type,display_name,required,quantity,due_at,instructions,position,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(slot.id,id,slot.articleType,slot.displayName,slot.required?1:0,slot.quantity,slot.dueAt,slot.instructions,slot.position,timestamp,timestamp)),...input.recipientStudentIds.map(studentId=>this.db.prepare('INSERT INTO assignment_targets(campaign_id,student_id) VALUES(?,?)').bind(id,studentId))]);return this.getCampaign(id);}
  async getCampaign(id){const campaign=parseCampaign(await this.db.prepare('SELECT * FROM assignment_campaigns WHERE id=?').bind(id).first());if(!campaign)return null;campaign.slots=(await this.db.prepare('SELECT * FROM assignment_slots WHERE campaign_id=? ORDER BY position,id').bind(id).all()).results.map(parseSlot);campaign.recipientStudentIds=(await this.db.prepare('SELECT student_id FROM assignment_targets WHERE campaign_id=?').bind(id).all()).results.map(x=>x.student_id);return campaign;}
  async listCampaigns(studentId){let q='SELECT DISTINCT c.* FROM assignment_campaigns c',args=[];if(studentId){q+=' JOIN assignment_recipients r ON r.campaign_id=c.id WHERE r.student_id=?';args.push(studentId);}q+=' ORDER BY c.created_at DESC';const rows=(await this.db.prepare(q).bind(...args).all()).results;return Promise.all(rows.map(row=>this.getCampaign(row.id)));}
  async updateCampaign(id,input){const timestamp=now();await this.db.prepare(`UPDATE assignment_campaigns SET name=?,year=?,issue_label=?,issue_id=?,instructions=?,starts_at=?,due_at=?,status=?,updated_at=? WHERE id=?`).bind(input.name,input.year,input.issueLabel,input.issueId,input.instructions,input.startsAt,input.dueAt,input.status,timestamp,id).run();return this.getCampaign(id);}
  async distributeCampaign(campaign,students){const timestamp=now(),statements=[];for(const student of students){statements.push(this.db.prepare(`INSERT INTO assignment_recipients(campaign_id,student_id,student_name,assigned_at) VALUES(?,?,?,?) ON CONFLICT(campaign_id,student_id) DO UPDATE SET student_name=excluded.student_name`).bind(campaign.id,student.id,student.name||'',timestamp));for(const slot of campaign.slots)for(let ordinal=1;ordinal<=slot.quantity;ordinal++)statements.push(this.db.prepare(`INSERT OR IGNORE INTO assignment_slot_instances(id,campaign_id,slot_id,student_id,ordinal,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),campaign.id,slot.id,student.id,ordinal,timestamp,timestamp));}statements.push(this.db.prepare(`UPDATE assignment_campaigns SET status='active',distributed_at=COALESCE(distributed_at,?),updated_at=? WHERE id=?`).bind(timestamp,timestamp,campaign.id));if(statements.length)await this.db.batch(statements);return this.getCampaign(campaign.id);}
  async listAssignments(studentId){let q=`SELECT asi.id,asi.campaign_id campaignId,asi.slot_id slotId,asi.student_id studentId,r.student_name studentName,asi.ordinal,asi.article_id articleId,c.name campaignName,c.year,c.issue_label issueLabel,c.instructions campaignInstructions,c.starts_at startsAt,c.due_at campaignDueAt,c.status campaignStatus,s.article_type articleType,s.display_name slotName,s.required,s.due_at slotDueAt,s.instructions slotInstructions,a.status articleStatus,a.updated_at articleUpdatedAt FROM assignment_slot_instances asi JOIN assignment_campaigns c ON c.id=asi.campaign_id JOIN assignment_slots s ON s.id=asi.slot_id JOIN assignment_recipients r ON r.campaign_id=asi.campaign_id AND r.student_id=asi.student_id LEFT JOIN articles a ON a.id=asi.article_id`;const args=[];if(studentId){q+=' WHERE asi.student_id=?';args.push(studentId);}q+=' ORDER BY c.due_at IS NULL,c.due_at,s.position,asi.ordinal';return (await this.db.prepare(q).bind(...args).all()).results;}
  async getAssignmentInstance(id){return this.db.prepare(`SELECT asi.*,c.status campaign_status,c.issue_id,s.article_type,s.display_name,s.instructions,s.due_at,c.due_at campaign_due_at FROM assignment_slot_instances asi JOIN assignment_campaigns c ON c.id=asi.campaign_id JOIN assignment_slots s ON s.id=asi.slot_id WHERE asi.id=?`).bind(id).first();}
  async createArticleForAssignment(instance,studentId){if(instance.article_id)return this.getNativeArticle(instance.article_id);const id=`assignment-${instance.id}`,timestamp=now(),title=instance.display_name+(instance.ordinal>1?` ${instance.ordinal}`:'');await this.db.batch([this.db.prepare(`INSERT OR IGNORE INTO articles(id,issue_id,student_id,article_type,title_ko,title_en,status,draft_html,created_at,updated_at) VALUES(?,?,?,?,?,?,'draft','',?,?)`).bind(id,instance.issue_id||null,studentId,instance.article_type,title,'',timestamp,timestamp),this.db.prepare(`UPDATE assignment_slot_instances SET article_id=?,updated_at=? WHERE id=? AND article_id IS NULL`).bind(id,timestamp,instance.id)]);const refreshed=await this.getAssignmentInstance(instance.id);return this.getNativeArticle(refreshed.article_id);}
}

export function repository(env) {
  if (!env.DB) throw Object.assign(new Error('D1 binding DB is required for production persistence.'), { status: 503, code: 'database_unconfigured' });
  return new D1EditorialRepository(env.DB);
}
