import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import worker,{validateCampaign} from '../src/index.js';
import {D1EditorialRepository} from '../src/repository.js';
import {seal,SESSION_COOKIE} from '../src/security.js';
import {normalizeLengthRules,lengthResult} from '../../assets/js/shared/length-rules.js';
import {submittedCharacterCount,validateSubmissionLength,reviewAssignmentLengths} from '../src/assignment-lengths.js';
const rules={minCharacters:3,maxCharacters:8};
test('0008 keeps preexisting assignments and old insert/update SQL compatible without indexes',()=>{
 const sql=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')&&!x.startsWith('0008')).sort())sql.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));
 const legacy="INSERT INTO assignment_campaigns(id,name,created_by_user_id,created_at,updated_at) VALUES('legacy','Legacy','admin','before','before')";sql.exec(legacy);const migration=readFileSync(new URL('../migrations/0008_assignment_lengths.sql',import.meta.url),'utf8');sql.exec(migration);assert.equal(sql.prepare("SELECT min_characters FROM assignment_campaigns WHERE id='legacy'").get().min_characters,null);sql.exec("UPDATE assignment_campaigns SET name='Changed' WHERE id='legacy'");assert.equal(sql.prepare("SELECT max_characters FROM assignment_campaigns WHERE id='legacy'").get().max_characters,null);assert.doesNotMatch(migration,/CREATE INDEX/);sql.close();
});
async function setup(limits={}){
 const f=fixture(),c=await f.repo.createCampaign(validateCampaign({name:'Length fixture',...limits,slots:[{articleType:'school',displayName:'학교기사'}]}),'admin');await f.repo.distributeCampaign(c,[{id:'student',name:'11001 학생'}]);
 const instance=f.sql.prepare('SELECT id FROM assignment_slot_instances').get();const a=await f.repo.createArticleForAssignment(await f.repo.getAssignmentInstance(instance.id),'student');
 await f.repo.saveStudentDraft(a.id,{articleType:'school',titleKo:'테스트',titleEn:'',contentHtml:'<p>본문</p>'});return {...f,c,article:()=>f.repo.getNativeArticle(a.id),id:a.id};
}
for(const [name,input,expected] of [['min',{minCharacters:3},[3,null]],['max',{maxCharacters:8},[null,8]],['both',rules,[3,8]],['disabled',{lengthEnabled:false,...rules},[null,null]],['legacy',{},[null,null]],['zero',{maxCharacters:0},[null,0]]])test('length rules '+name,()=>{const r=normalizeLengthRules(input);assert.deepEqual([r.minCharacters,r.maxCharacters],expected);});
test('length rules reject invalid or equal/reversed values',()=>{for(const input of [{minCharacters:-1},{minCharacters:1.1},{minCharacters:' '},{minCharacters:true},{minCharacters:3,maxCharacters:3},{minCharacters:9,maxCharacters:8},{lengthEnabled:true},{maxCharacters:Infinity}])assert.throws(()=>normalizeLengthRules(input));});
test('one existing grapheme/text counter includes spaces, paragraph/BR and CRLF boundaries',()=>{for(const [html,count] of [['<p>A  B</p>',4],['<p>한글</p><p>English</p>',10],['<p>A<br>B</p>',3],['<p>A\r\nB</p>',3],['<p>é 👩‍💻</p>',3],['<p>&copy;&nbsp;&amp;&#x1f600;</p>',4],['<p>A</p><!--x--><p>B</p>',3],['<p><br></p>',0],['<script>bad</script><p>ok</p>',2]])assert.equal(submittedCharacterCount(html),count,html);});
test('submit validation rejects below/above while keeping in-range and legacy valid',()=>{for(const count of [0,2,9])assert.throws(()=>validateSubmissionLength({draftHtml:'A'.repeat(count),...rules}),e=>e.code==='article_length_out_of_range');for(const count of [3,8])assert.equal(validateSubmissionLength({draftHtml:'A'.repeat(count),...rules}).allowed,true);assert.equal(validateSubmissionLength({draftHtml:'A'.repeat(20)}).allowed,true);});
test('migration defaults and stored min/max roundtrip; changing limits never changes status',async()=>{const f=await setup();assert.equal((await f.article()).minCharacters,null);await f.repo.submitNativeArticle(await f.article(),'student');await f.repo.updateCampaign(f.c.id,{...await f.repo.getCampaign(f.c.id),...rules});assert.equal((await f.article()).status,'submitted');assert.equal((await f.article()).minCharacters,3);assert.equal((await f.repo.listCampaigns('student'))[0].maxCharacters,8);f.sql.close();});
test('dry-run is read-only, counts last student submission and bulk preserves feedback/internal note',async()=>{
 const f=await setup();await f.repo.submitNativeArticle(await f.article(),'student');await f.repo.saveEditorDraft(await f.article(),{contentHtml:'A'.repeat(100),studentFeedback:'기존 피드백',internalNote:'SECRET'},'admin');
 const preview=await reviewAssignmentLengths(f.db,f.repo,f.c.id,rules,{sub:'admin'},'secret');assert.equal(preview.targets[0].count,2);assert.equal(preview.below,1);assert.equal((await f.article()).status,'submitted');assert.equal((await f.repo.getCampaign(f.c.id)).minCharacters,null);assert.doesNotMatch(JSON.stringify(preview),/SECRET|submittedHtml/);
 const result=await reviewAssignmentLengths(f.db,f.repo,f.c.id,{...rules,token:preview.token,confirmation:'반려'},{sub:'admin'},'secret',true);assert.equal(result.rejectedCount,1);const a=await f.article();assert.equal(a.status,'revision_requested');assert.match(a.studentFeedback,/기존 피드백[\s\S]*1자 부족/);assert.equal(a.internalNote,'SECRET');assert.equal(a.currentStudentRevisionId,(await f.repo.listRevisions(f.id)).find(r=>r.authorRole==='student').id);
 assert.equal((await reviewAssignmentLengths(f.db,f.repo,f.c.id,{...rules,token:preview.token,confirmation:'반려'},{sub:'admin'},'secret',true)).replayed,true);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM assignment_length_reviews').get().n,1);f.sql.close();
});
for(const status of ['approved','scheduled','draft','revision_requested','hold'])test('bulk does not return protected or inactive '+status,async()=>{const f=await setup();await f.repo.submitNativeArticle(await f.article(),'student');await f.repo.setNativeStatus(await f.article(),status,'admin');const p=await reviewAssignmentLengths(f.db,f.repo,f.c.id,rules,{sub:'admin'},'secret');assert.equal(p.targets.length,0);assert.equal(p.completedOutside.length,['approved','scheduled'].includes(status)?1:0);assert.equal((await f.article()).status,status);f.sql.close();});
test('missing submission history is reported and preserved, never counts teacher/current draft',async()=>{const f=await setup();f.sql.prepare("UPDATE articles SET status='submitted' WHERE id=?").run(f.id);const p=await reviewAssignmentLengths(f.db,f.repo,f.c.id,rules,{sub:'admin'},'s');assert.equal(p.unverifiable.length,1);assert.equal(p.targets.length,0);f.sql.close();});
test('changed preview, actor or limits cannot be applied',async()=>{const f=await setup();await f.repo.submitNativeArticle(await f.article(),'student');const p=await reviewAssignmentLengths(f.db,f.repo,f.c.id,rules,{sub:'admin'},'s');await f.repo.setNativeStatus(await f.article(),'reviewing','admin');await assert.rejects(reviewAssignmentLengths(f.db,f.repo,f.c.id,{...rules,token:p.token,confirmation:'반려'},{sub:'admin'},'s',true),e=>e.code==='stale_length_review');await assert.rejects(reviewAssignmentLengths(f.db,f.repo,f.c.id,{...rules,token:p.token,confirmation:'반려'},{sub:'other'},'s',true),e=>e.status===400);f.sql.close();});
test('transaction guard rolls back every write if submission changes after recomputation',async()=>{const f=await setup();await f.repo.submitNativeArticle(await f.article(),'student');const p=await reviewAssignmentLengths(f.db,f.repo,f.c.id,rules,{sub:'admin'},'s'),batch=f.db.batch;f.db.batch=async statements=>{f.sql.prepare("UPDATE articles SET status='approved' WHERE id=?").run(f.id);return batch(statements);};await assert.rejects(reviewAssignmentLengths(f.db,f.repo,f.c.id,{...rules,token:p.token,confirmation:'반려'},{sub:'admin'},'s',true),e=>e.code==='stale_length_review');assert.equal((await f.article()).status,'approved');assert.equal((await f.repo.getCampaign(f.c.id)).minCharacters,null);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM assignment_length_reviews').get().n,0);f.sql.close();});
test('submit compare-and-set rejects concurrent body or assignment limit change',async()=>{const f=await setup(),old=await f.article();await f.repo.updateCampaign(f.c.id,{...await f.repo.getCampaign(f.c.id),...rules});await assert.rejects(f.repo.submitNativeArticle(old,'student'),e=>e.code==='stale_submission');assert.equal((await f.article()).status,'draft');assert.equal((await f.repo.listRevisions(f.id)).length,0);f.sql.close();});
test('student cannot change limits, inspect or bulk reject; CSRF and anonymous access blocked',async t=>{const f=await setup(),send=await auth(t,f,'student');for(const suffix of ['length-preview','length-apply']){const response=await send(`/api/assignments/${f.c.id}/${suffix}`,'POST',rules);assert.equal(response.status,403);assert.match(response.headers.get('cache-control'),/no-store/);}assert.equal((await send(`/api/assignments/${f.c.id}`,'PATCH',rules)).status,403);const anon=await worker.fetch(new Request(`https://local.test/api/assignments/${f.c.id}/length-apply`,{method:'POST',headers:{Origin:'https://evil.test'}}),{DB:f.db,SESSION_SECRET:'s'});assert.notEqual(anon.status,200);f.sql.close();});
test('actual student submit API rejects outside limits without changing status; save remains available',async t=>{const f=await setup(rules),send=await auth(t,f,'student');const r=await send(`/api/native/articles/${f.id}/submit`,'POST',{});assert.equal(r.status,400);assert.equal((await r.json()).error.code,'article_length_out_of_range');assert.equal((await f.article()).status,'draft');const save=await send(`/api/native/articles/${f.id}`,'PATCH',{articleType:'school',titleKo:'테스트',contentHtml:'<p>본문 수정</p>'});assert.equal(save.status,200);assert.equal((await send(`/api/native/articles/${f.id}/submit`,'POST',{})).status,200);f.sql.close();});
test('max-only bulk feedback and disabling rules preserve existing submission states',async()=>{const f=await setup();await f.repo.submitNativeArticle(await f.article(),'student');const max={maxCharacters:1},p=await reviewAssignmentLengths(f.db,f.repo,f.c.id,max,{sub:'admin'},'s');assert.equal(p.above,1);await reviewAssignmentLengths(f.db,f.repo,f.c.id,{...max,token:p.token,confirmation:'반려'},{sub:'admin'},'s',true);assert.match((await f.article()).studentFeedback,/최대 1자[\s\S]*1자 초과/);await f.repo.updateCampaign(f.c.id,{...await f.repo.getCampaign(f.c.id),...normalizeLengthRules({lengthEnabled:false})});assert.equal((await f.article()).status,'revision_requested');assert.equal((await f.article()).maxCharacters,null);f.sql.close();});
test('resubmission uses latest student submission, not import or teacher revision',async()=>{const f=await setup();await f.repo.submitNativeArticle(await f.article(),'student');await f.repo.setNativeStatus(await f.article(),'revision_requested','admin');await f.repo.saveStudentDraft(f.id,{articleType:'school',titleKo:'테스트',titleEn:'',contentHtml:'123456'});await f.repo.submitNativeArticle(await f.article(),'student');await f.repo.saveEditorDraft(await f.article(),{contentHtml:'x',checkpoint:true},'admin');const p=await reviewAssignmentLengths(f.db,f.repo,f.c.id,rules,{sub:'admin'},'s');assert.equal(p.valid,1);assert.equal(p.targets.length,0);f.sql.close();});
test('above-max direct submit API is blocked; no revision created',async t=>{const f=await setup({maxCharacters:1}),send=await auth(t,f,'student');assert.equal((await send(`/api/native/articles/${f.id}/submit`,'POST',{})).status,400);assert.equal((await f.repo.listRevisions(f.id)).length,0);f.sql.close();});
test('valid admin preview/apply endpoints use existing authorization and preserve no-store',async t=>{const f=await setup();await f.repo.submitNativeArticle(await f.article(),'student');const send=await auth(t,f);const response=await send(`/api/assignments/${f.c.id}/length-preview`,'POST',rules);assert.equal(response.status,200);assert.match(response.headers.get('cache-control'),/no-store/);const p=await response.json();const done=await send(`/api/assignments/${f.c.id}/length-apply`,'POST',{...rules,token:p.token,confirmation:'반려'});assert.equal(done.status,200);assert.equal((await f.article()).status,'revision_requested');f.sql.close();});
function fixture(){
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));
 const calls=[];const db={prepare(query){let args=[];const stmt={bind(...values){args=values;return stmt;},async first(){calls.push(query);return sql.prepare(query).get(...args)??null;},async all(){calls.push(query);return {results:sql.prepare(query).all(...args)};},async run(){calls.push(query);return sql.prepare(query).run(...args);}};return stmt;},async batch(items){sql.exec('BEGIN');try{const result=await Promise.all(items.map(x=>x.run()));sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};return {sql,db,calls,repo:new D1EditorialRepository(db)};
}
async function auth(t,f,role='admin'){
 t.mock.method(globalThis,'fetch',async url=>{url=String(url);if(url.includes('userProfiles'))return Response.json({id:role});if(url.includes('/teachers/'))return role==='admin'?Response.json({userId:role}):new Response('',{status:404});if(url.endsWith('/students?pageSize=100'))return Response.json({students:[{userId:'g1',profile:{name:{fullName:'11001 Student'}}},{userId:'g3',profile:{name:{fullName:'31001 Alumni'}}}]});return Response.json({userId:role});});
 const env={DB:f.db,SESSION_SECRET:'fixture',NEWSPAPER_CLASSROOM_ID:crypto.randomUUID()};const token=await seal({sub:role,accessToken:'fixture',courseId:env.NEWSPAPER_CLASSROOM_ID,exp:Date.now()+60000},env.SESSION_SECRET);
 return (path,method='GET',body,extraHeaders={})=>worker.fetch(new Request('https://local.test'+path,{method,headers:{Cookie:SESSION_COOKIE+'='+token,Origin:'https://local.test','X-Editorial-CSRF':'1','Content-Type':'application/json',...extraHeaders},...(body?{body:JSON.stringify(body)}:{})}),env);
}

test('admin bulk endpoints reject missing CSRF and untrusted origin',async t=>{const f=await setup(),send=await auth(t,f);for(const suffix of ['length-preview','length-apply'])for(const headers of [{'X-Editorial-CSRF':'0'},{Origin:'https://evil.test'}])assert.equal((await send('/api/assignments/'+f.c.id+'/'+suffix,'POST',rules,headers)).status,403);f.sql.close();});
